version: 2

models:
  - name: stg_jaffle_shop__customers
    description: "Staging model for jaffle shop customers data"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_jaffle_shop__orders
    description: "Staging model for jaffle shop orders data"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
